Some tasks have been completed
js-tasks-ru/js-20200928_alex182 pull request #4
Opened 2020-10-21 13:55 UTC by taksoidet

2020-10-21 14:14 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-21 22:21 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-10-24 21:31 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +export default class SortableTable extends SortableTableV1 {
здесь нет потребности что-то наследовать, каждая новая версия компонента - это как улучшения ее функциональности, без потребности использовать старую версию.
Это нужно поправить

2020-10-24 21:32 UTC, dosandk requested changes
необходимо исправить решение "SortableTable" компонента

2020-10-25 01:49 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
SortableTable компонент - без обработчиков событий клика и динамической загрузки
+ should be rendered correctly
+ should not have default sorting
+ should sort "asc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal string
+ should sort "asc" correctly for "sortType" equal number
+ should sort "desc" correctly for "sortType" equal number
+ should have ability to be destroyed
```
```diff
SortableTable v2 компонент без динамической загрузки данных
+ should be rendered correctly
+ should have default sorting marked by arrow icon
+ should sort "desc" correctly for "sortType" equal string
+ should sort "desc" correctly for "sortType" equal number
+ should move arrow icon to the corresponding column after sorting
+ should have ability to be destroyed
```
```diff
ColumnChart компонент
+ should be rendered correctly
+ should have ability to define label
+ should have ability to define link
+ should have ability to define total value
+ should have property 'chartHeight
+ should render data correctly
+ should have ability to be updated by new "data" values (should re-render only body with charts columns)
+ should have loading indication if data wasn't passed 
+ should have ability to be removed
```
```diff
NotificationMessage компонент
+ should be rendered correctly
+ should have ability to set duration
+ should be removed after time defined in duration property
+ should have ability to set message
+ should have ability to set 'success' type of message
+ should have ability to set 'error' type of message
+ should have ability to define target element for rendering
+ should have ability to be destroyed
```
```diff
Tooltip компонент
+ should be rendered correctly
+ should be shown when moving over the element with data-tooltip attribute
+ should be hidden when moving out from the element with data-tooltip attribute
+ should have ability to be destroyed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-25 16:25 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-26 02:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-27 18:58 UTC, dosandk approved these changes
good 👍

2020-10-27 19:00 UTC, merged